services:
  users-postgres:
    image: postgres:17
    container_name: users-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

  users-api:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    container_name: users-api
    ports:
      - "8092:8092"
    environment:
      POSTGRES_HOST: users-postgres
      POSTGRES_PORT: 5432
    depends_on:
      users-postgres:
        condition: service_healthy
